#!/usr/bin/env bash
#
# Devcontainer post-start.
#
# Runs via postStartCommand, where stdout is often not a TTY — so both `clear`
# and the ANSI colors are gated on an interactive terminal.
#
# The host is not assumed to have any AWS configuration: nothing is bind-mounted
# from ~/.aws. Instead the whole profile is materialised here from environment
# variables supplied through .devcontainer/devcontainer.env (git-ignored, seeded
# from devcontainer.env.example). The SSO token cache lives in a named Docker
# volume, so `aws sso login` survives container rebuilds.

set -euo pipefail

if [ -t 1 ]; then
    clear
    green=$'\033[0;32m'
    yellow=$'\033[0;33m'
    dim=$'\033[0;90m'
    reset=$'\033[0m'
else
    green='' yellow='' dim='' reset=''
fi

# Workspace name from $PWD (lifecycle commands run in the workspace folder).
# Passed as a printf *argument*, never in the format string — a directory name
# containing '%' would otherwise be parsed as a format specifier.
printf '%sDevSecOps Dev Container: %s%s\n' "${green}" "${PWD##*/}" "${reset}"

if command -v devcontainer-info >/dev/null 2>&1; then
    devcontainer-info || true
fi

# -----------------------------------------------------------------------------
# AWS profile
# -----------------------------------------------------------------------------

AWS_DIR="${HOME}/.aws"
AWS_CONFIG="${AWS_DIR}/config"

profile="${AWS_PROFILE:-default}"
region="${AWS_REGION:-eu-north-1}"
sso_session="${AWS_SSO_SESSION:-sso}"

# A value still holding its placeholder counts as unset — devcontainer.env is
# seeded from the example file on first start, so this is the normal state
# until someone fills it in.
is_set() {
    case "${1:-}" in
        '' | *your-sso-portal* | *123456789012*) return 1 ;;
        *) return 0 ;;
    esac
}

mkdir -p "${AWS_DIR}"

if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
    printf '%saws%s  static credentials from the environment (profile: %s)\n' \
        "${green}" "${reset}" "${profile}"

elif is_set "${AWS_SSO_START_URL:-}" && is_set "${AWS_SSO_ACCOUNT_ID:-}"; then
    # Regenerated on every start so devcontainer.env stays the single source of
    # truth; only ~/.aws/sso/cache (the volume) carries state across restarts.
    cat > "${AWS_CONFIG}" <<EOF
# Generated by .devcontainer/post-start.sh — edit devcontainer.env, not this.
[sso-session ${sso_session}]
sso_start_url = ${AWS_SSO_START_URL}
sso_region = ${AWS_SSO_REGION:-${region}}
sso_registration_scopes = sso:account:access

[profile ${profile}]
sso_session = ${sso_session}
sso_account_id = ${AWS_SSO_ACCOUNT_ID}
sso_role_name = ${AWS_SSO_ROLE_NAME:-AdministratorAccess}
region = ${region}
output = json
EOF
    chmod 600 "${AWS_CONFIG}"

    if aws sts get-caller-identity >/dev/null 2>&1; then
        printf '%saws%s  profile %s active in %s\n' \
            "${green}" "${reset}" "${profile}" "${region}"
    else
        printf '%saws%s  profile %s written, no valid session — run %stask aws:login%s\n' \
            "${yellow}" "${reset}" "${profile}" "${green}" "${reset}"
    fi

else
    printf '%saws%s  not configured — fill in %s.devcontainer/devcontainer.env%s and restart\n' \
        "${yellow}" "${reset}" "${dim}" "${reset}"
fi

if command -v task >/dev/null 2>&1; then
    printf '%s→ run %stask%s%s to list the available commands%s\n' \
        "${dim}" "${reset}" "${green}" "${dim}" "${reset}"
fi
